Amsterdam/signalen

- domains/amsterdamsebos/acc.config.json
- domains/amsterdamsebos/prod.config.json
This PR updates the Amsterdamse Bos configuration with search capabilities for Amstelveen
> [SIG-3028] Add Amstelveen to the location search

- domains/amsterdam/acc.config.json
- domains/amsterdam/prod.config.json
- domains/amsterdamsebos/acc.config.json
- domains/amsterdamsebos/prod.config.json
- domains/weesp/acc.config.json
- domains/weesp/prod.config.json
This PR updates the text of consentToContactSharing setting
> [SIG-3038] Updates the text of the consentToContactSharing setting

- domains/amsterdam/acc.config.json
- domains/amsterdam/prod.config.json
- domains/amsterdamsebos/acc.config.json
- domains/amsterdamsebos/prod.config.json
- domains/weesp/acc.config.json
- domains/weesp/prod.config.json
Adds `useStaticMapServer` to all confs
> (Chore) Add config props to acc conf

- domains/amsterdamsebos/acc.config.json
- domains/amsterdamsebos/prod.config.json
This PR fixes the site name configuration for Amsterdamse Bos
> [SIG-3063] Change the page title for the AmsterdamseBos configuration

- domains/amsterdam/acc.config.json
- domains/amsterdam/prod.config.json
- domains/amsterdamsebos/acc.config.json
- domains/amsterdamsebos/prod.config.json
- domains/weesp/acc.config.json
- domains/weesp/prod.config.json
This PR adds the following props:
- `district`
- `fetchDistrictsFromBackend` (see https://github.com/Amsterdam/signals-frontend/pull/1026) and
- `fetchSourcesFromBackend` (see https://github.com/Amsterdam/signals-frontend/pull/1065)
> (Chore) Config props

- domains/amsterdam/acc.config.json
- domains/amsterdam/prod.config.json
- domains/amsterdamsebos/acc.config.json
- domains/amsterdamsebos/prod.config.json
- domains/weesp/acc.config.json
- domains/weesp/prod.config.json
This PR changes the HTML page titles, the manifest name and the site header title for logged in users for all domains.
> [SIG-3137] Domain page titles

- domains/amsterdamsebos/acc.config.json
- domains/amsterdamsebos/prod.config.json
- domains/weesp/acc.config.json
- domains/weesp/prod.config.json
This PR configures the correct site addresses for the weesp and amsterdamsebos versions
> (Bug) Fixes the siteAddress for weesp and amsterdamsebos

- domains/weesp/acc.config.json
- domains/weesp/prod.config.json
This PR
- changes the Weesp phone number
- changes the opening hours text
- disables the additional questions
> [SIG-3250] Changes the phone number and disables additional questions for Weesp 

- domains/amsterdam/prod.config.json
- domains/amsterdamsebos/prod.config.json
- domains/weesp/prod.config.json
- This should be temporary and moved to the oidc configuration after Grip has been turned off
- **BEFORE MERGE** check if the *realm* is correct!
> [SIG-3207] Add Keycloak configuration

- domains/amsterdam/prod.config.json
- domains/amsterdamsebos/prod.config.json
- domains/weesp/prod.config.json
- Keycloak realm changed from datapunt-ad to datapunt-ad-b
> [SIG-3207] Updates Keycloak realm production value

- Jenkinsfile.acceptance
- Jenkinsfile.release
- domains/amsterdam/Dockerfile
- domains/amsterdamsebos/Dockerfile
- domains/weesp/Dockerfile
- vars/deployDomains.groovy
- vars/signalen.groovy
Jenkins groundwork for running SIA pipelines in docker.
> (Chore) Changes for preparing running Jenkins in Docker

- domains/weesp/acc.config.json
This PR enables the extra questions for the weesp configuration
> [SIG-3631] Enable the extra questions for the weesp configuration

- domains/weesp/acc.config.json
This PR reverts the enabling of te extra questions in the weesp configuration
> [SIG-3631] Disable the extra questions for weesp

- packages/siali/src/commands/release.ts
This PR updates the `siali` configuration flags when these are provided. After upgrading the github access token there was no easy way to do that.
> (Core) Update the configuration flag iif provided

- domains/amsterdam/prod.config.json
- domains/amsterdamsebos/prod.config.json
- domains/weesp/prod.config.json
> Revert "(Chore) Updates keycloak realm"

- package-lock.json
- packages/siali/README.md
- packages/siali/src/lib/issue.interface.ts
- packages/siali/src/lib/release.service.ts
This PR:
- mentions Jira account language settings as a requirement 
- fixes missing references for `subtask` issue type
> (Chore) Update docs

- Jenkinsfile.acceptance
- Jenkinsfile.release
- domains/app/Dockerfile
- domains/app/acceptance.config.json
- domains/app/production.config.json
Adds configuration for the `app.meldingen.amsterdam.nl` domain
> [SIG-3969] App Jenkins config

- vars/signalenReleasePipeline.groovy
Adds `app` domain to Jenkins deploy config
> (Chore) Add missing domain

- domains/amsterdam/acceptance.config.json
- domains/amsterdam/production.config.json
- domains/amsterdamsebos/acceptance.config.json
- domains/amsterdamsebos/production.config.json
- domains/weesp/acceptance.config.json
- domains/weesp/production.config.json
This PR adds the feature flag `showThorButton` to the appropriate configurations. Completes PR https://github.com/Amsterdam/signals-frontend/pull/1864.
> (Chore) Show THOR button

- vars/buildAndPushSignalsFrontendDockerImage.groovy
Contains fix for deployment script for a wrongly referenced var
> (Fix) gitRef

- vars/buildAndPushSignalsFrontendDockerImage.groovy
- vars/signalenAcceptancePipeline.groovy
- vars/signalenReleasePipeline.groovy
Removes optional var from `buildAndPushSignalsFrontendDockerImage`
> (Chore) Remove optional var

- domains/amsterdamsebos/acceptance.config.json
- domains/amsterdamsebos/production.config.json
- domains/app/acceptance.config.json
- domains/app/production.config.json
- domains/weesp/acceptance.config.json
- domains/weesp/production.config.json
for weesp, amsterdamse bos, and app
> [SIG-4118] Help text in configuration language

- domains/amsterdam/acceptance.config.json
- domains/amsterdam/production.config.json
- domains/amsterdamsebos/acceptance.config.json
- domains/amsterdamsebos/production.config.json
- domains/app/acceptance.config.json
- domains/app/production.config.json
- domains/weesp/acceptance.config.json
- domains/weesp/production.config.json
Removes all config entries that have already been covered by the contents of `app.amsterdam.json` in the `signals-frontend` repository.
> [SIG-4164] Correct phone number

- packages/siali/.eslintrc.js
- packages/siali/package.json
- packages/siali/yarn.lock
- updated @oclif/dev-cli
- removed eslint-plugin-graphql
> Remove security vulnerabilities in siali

- domains/amsterdamsebos/acceptance.config.json
- domains/amsterdamsebos/production.config.json
- domains/weesp/acceptance.config.json
- domains/weesp/production.config.json
This is to comply with https://github.com/Amsterdam/signals-frontend/pull/2123
> Municipality type from array to string

- domains/weesp/acceptance.config.json
- domains/weesp/production.config.json
Adjusted the alt text of the municipality logo according to [this ticket](https://datapunt.atlassian.net/browse/SIG-4697)
> Adjusted logo alt text
